### ISSUE TITLE
Doesn't work with artifacts uploaded not through workflow yaml

### ISSUE THREAD

**Issue by KOLANICH** [oprypin/nightly.link#1]
I mean I upload artifacts from a shell script (by cloning the action git repo and invoking the script manually) without declaring them in a yaml file explicitly.

**Comment by oprypin** [comment]
Probably not going to support this. But in any case, can you provide details??? Just how to do this "invoking the script"

**Comment by KOLANICH** [comment]
Just clone the repo, then set env vars, then call `node <path to cloned repo>/<js file mentioned in action.yml>`. Uploading artifacts requires some env vars exposed only to node.js environment, so either passing them through is needed (I have created an action for that, but using it would require modification of every workflow file requiring uploading from a workflow, just calling bash from node.js is easier and better scalable) or the shell script should be executed from a script for node.js.

**Comment by oprypin** [comment]
I am not familiar with this at all. If you don't post a repository that does exactly this, I can't do anything. Well I probably won't do anything anyway :/

**Comment by KOLANICH** [comment]
https://github.com/KOLANICH/webext-experiment-config

The pipeline fails, but it doesn't matter, the artifact is still uploaded.

**Comment by oprypin** [comment]
Right... As I expected, you incorrectly guessed the cause of this issue.

It works: https://nightly.link/KOLANICH/webext-experiment-config/actions/artifacts/29138561

But only successful runs are considered when finding the "latest".

**Comment by KOLANICH** [comment]
Thanks for the info. The form on the main page of the website asks to provide a link to workflow main file and errors if that file has no upload action.
