### ISSUE TITLE
[Feature request] permanent link to logs

### ISSUE THREAD

**Issue by B0pol** [oprypin/nightly.link#11]
You can see logs with "view raw logs" in the three dots menu. It also gives 404 when not logged in and a non-permanent link

**Comment by oprypin** [comment]
Your assessment seems correct and thanks for letting me know.

1. I am curious about the use case in general; can't you just share *non*-raw logs with people?

2. Do you want to share the latest logs or logs of a particular run?

3. In either case, what kind of workflow do you expect to go through when creating a link?

**Comment by oprypin** [comment]
^I implemented the only way I see it right now, but I will want to hear your response.

**Comment by B0pol** [comment]
1. The UI / UX is horrible, I can't even search with browser search function, it is like 500 px high

2. A particular run would be nice.
3. I put the url of the CI on the main page, I have access to the log.

Also another feature request, related to workflow: it would be amazing to just put the run in the bar and get access to the specific log, and artifacts if they exist. That's how I imagined when I replies to 2.

**Comment by oprypin** [comment]
> I put the url of the CI on the main page, I have access to the log.

Example URL?

**Comment by B0pol** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/runs/1863558315

**Comment by B0pol** [comment]
nevermind, that is an example URL for a run, for
> it would be amazing to just put the run URL in the bar and get access to the specific log, and artifacts if they exist. 

for the CI:
https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/.github/workflows/ci.yml

**Comment by oprypin** [comment]
No I'm pretty sure the link that you edited out was the one I wanted

**Comment by oprypin** [comment]
OK this inspired a pretty amazing expansion in functionality, and I think I satisfied almost all the secondary feature requests as well.
Not released yet, though.

**Comment by oprypin** [comment]
Now this is all possible.

Check out https://nightly.link/ with its updated instructions and let me know if it's difficult to figure out how to get things done.

**Comment by B0pol** [comment]
Thank you

**Comment by B0pol** [comment]
https://nightly.link/TeamNewPipe/NewPipeExtractor/actions/runs/563690418

There are no logs available?

**Comment by oprypin** [comment]
Please read the new section "Extra links for a particular run"
