### ISSUE TITLE
Let's Encrypt SSL cert expiry

### ISSUE THREAD

**Issue by EmulationFanatic** [oprypin/nightly.link#13]
The Nightly.link SSL cert has expired.

**Comment by oprypin** [comment]
Wow.
Thanks certbot for arbitrarily deciding to create the file as
`/etc/letsencrypt/live/nightly.link-0003/privkey.pem` instead of the usual
`/etc/letsencrypt/live/nightly.link/privkey.pem`

And thanks for the tipoff :>
