### ISSUE TITLE
Handle # (symbol)

### ISSUE THREAD

**Issue by ryota-hasegawa** [oprypin/nightly.link#15]
Artifacts have # in their file names can't be downloaded.

Example: https://github.com/MuntashirAkon/AppManager/actions/runs/709150441

Result on `https://nightly.link/MuntashirAkon/AppManager/actions/runs/709150441/AppManager_v2.6.0-DEBUG#1072.zip`
```
Error 404 – Not Found

Artifact 'AppManager_v2.6.0-DEBUG' not found for run #709150441.

Check on GitHub: https://github.com/MuntashirAkon/AppManager/actions/runs/709150441#artifacts
```
But `https://nightly.link/MuntashirAkon/AppManager/actions/runs/709150441/AppManager_v2.6.0-DEBUG%231072.zip` works

**Comment by oprypin** [comment]
Thanks for the report! I have fixed this but not deployed it yet.

**Comment by oprypin** [comment]
Deployed

**Comment by ryota-hasegawa** [comment]
It worked. Thank you :)
