### ISSUE TITLE
Allow runs that are triggered by events other than push

### ISSUE THREAD

**Issue by SamSchott** [oprypin/nightly.link#17]
It seems that currently only runs which where triggered by a push are supported:

https://github.com/oprypin/nightly.link/blob/0a7c5ae5e167c24016c42ddbfa9f9f14b24ab7b0/src/nightly_link.cr#L421

Am I reading this correctly? If yes, would you consider support "schedule" events as well (e.g., for actual nighty builds)?

**Comment by oprypin** [comment]
No, it supports 'schedule'.

https://github.com/oprypin/nightly.link/blob/0a7c5ae5e167c24016c42ddbfa9f9f14b24ab7b0/src/nightly_link.cr#L401-L405

You're looking at a line that's handling what happens if no build at all is found, and anyway this only produces a link for the user to click and see that there's indeed nothing to see on GitHub.

**Comment by SamSchott** [comment]
Ok, thanks for the quick reply! In that case, the issue is that it didn't find the builds in the first place. But that is probably on my side.

**Comment by oprypin** [comment]
Hmm what we're looking at right now is the fact that this query returns an empty result:

https://api.github.com/repos/samschott/maestral-cocoa/actions/workflows/pythonpublish.yml/runs?per_page=1&branch=master&event=schedule&status=success

**Comment by oprypin** [comment]
Hmm nevermind... which repo and workflow is the one that you are having problems with, anyway?

**Comment by SamSchott** [comment]
Yeah, the issue was on my side. I was pointing it to the wrong workflow. `pythonpublish.yml` builds and pushes wheels to PyPI, I really needed `build.yml` which builds the app bundle and publishes a GH artifact 🤦

**Comment by SamSchott** [comment]
It works perfectly now, thanks!
