### ISSUE TITLE
Doesn't work for organizations's private repos

### ISSUE THREAD

**Issue by stasbel** [oprypin/nightly.link#18]
Getting "Error 404 – Not Found" every time I past the links to workflows.

**Comment by oprypin** [comment]
But did you do what's required to make it work?

![Screenshot_20210414-135735_Firefox Beta](https://user-images.githubusercontent.com/371383/114706651-82496480-9d29-11eb-8c79-206a119f64c4.png)

**Comment by stasbel** [comment]
yes, I did
both authorizing and installing it for the org

**Comment by stasbel** [comment]
I can see list of private repos at https://nightly.link/dashboard, but I still got 404 after inserting the workflow link.

**Comment by oprypin** [comment]
Alrighty... I broke that in https://github.com/oprypin/nightly.link/commit/0e3b915a04811290b03e71bdf55b23e7ccc75405#diff-7286177a570f73a68394ee05dd63757b5687e6972f0c23af9a3e656cab0043f4L188 :confounded: 

Apologies

I have deployed the fix now

**Comment by SaeedMasoumi** [comment]
@oprypin "Link to a particular artifact" is not working on private repos of the organization.

**Comment by oprypin** [comment]
> But did you do what's required to make it work?
> 
> ![Screenshot_20210414-135735_Firefox Beta](https://user-images.githubusercontent.com/371383/114706651-82496480-9d29-11eb-8c79-206a119f64c4.png)

**Comment by SaeedMasoumi** [comment]
@oprypin Yes, I can see my projects from the dashboard. 
This format will not work until `?h={hash}` added to the url
https://nightly.link/{org}/{project}/workflows/{file}.yaml/master/release-apk
So
https://nightly.link/{org}/{project}/workflows/{file}.yaml/master/release-apk?h=33csxxxxx
this works properly, but I don't know what is h and how it can received. I want to generate this link on CI and send it to a slack channel.

**Comment by oprypin** [comment]
Well you received the `h` once already. Then you can keep using it for the same repo.

Note that if you publish this link with the hash, anyone will be able to download your binary from your private repo.

The requirement for this secret hash is to prevent random people from downloading anything from any private repo.

**Comment by andybak** [comment]
I just discovered that the url containing the hash allows _anyone_ to access builds.

I was surprised as I assumed the downloads would still go through Github's permission system. 

I'm guessing there's no way to use nightly.build to create permanent links that still respect membership of a private repo?

**Comment by oprypin** [comment]
> I just discovered that the url containing the hash allows anyone to access builds.

Yes, that's very much intended, I don't know why you expected otherwise. That hash is a password. If it was intended to "respect membership" then there would be no need for that password.

**Comment by vinaghost** [comment]
@oprypin how do I generate that hash? 
i used this line for public repo but since it required hash, i have no idea how get it works
```
 message: Click [here](https://nightly.link/vinaghost/{my_repo}/actions/runs/${{ github.run_id }}) to check the build
```

**Comment by oprypin** [comment]
@vinaghost  You need to click "authorize to see your repositories" at https://nightly.link/

It is a secret that cannot be generated in any other way. (and the source code to verify that is public, but the base secret key isn't)

**Comment by vinaghost** [comment]
@oprypin thanks for reply, i saw the hash from that button, i wonder when that hash change or it will same until i un-link repo ?

**Comment by oprypin** [comment]
same
