### ISSUE TITLE
Allow downloading artifacts without the suite ID

### ISSUE THREAD

**Issue by EricRabil** [oprypin/nightly.link#19]
I'm making a nightly releases page that shows the latest artifacts, using the [List artifacts for a repository](https://docs.github.com/en/rest/reference/actions#list-artifacts-for-a-repository) endpoint. This endpoint does not provide suite IDs, only the artifact IDs. It also provides an `archive_download_url`, which, when accessed, redirects you to an ephemeral download URL.

Would it be possible for nightly.link to support either downloading an artifact given:
1. Username
2. Repo name
3. Artifact ID

**or**

by just proxying URLs of the format `https://api.github.com/repos/octo-org/octo-docs/actions/artifacts/11/zip`, perhaps as `https://api.nightly.link/repos/octo-org/octo-docs/actions/artifacts/11/zip`?

In the meantime, [here's a stopgap](https://github.com/EricRabil/damnit-github-actions) I made so that I could proceed with the downloads page.

**Comment by oprypin** [comment]
Can you provide a real example of 

> 1. Username
> 2. Repo name
> 3. Artifact ID

also suite ID for posteriry

**Comment by EricRabil** [comment]
Yeah, sorry

```
Download link from the artifacts section of the UI:

                   USERNAME  REPO          SUITE ID             ARTIFACT ID
https://github.com/EricRabil/BBDash/suites/2569081819/artifacts/55984571

Download link from the API:

                             USERNAME  REPO                     ARTIFACT ID
https://api.github.com/repos/EricRabil/BBDash/actions/artifacts/55984571/zip
```

**Comment by oprypin** [comment]
This already works, as https://nightly.link/EricRabil/BBDash/actions/artifacts/55984571 [.zip]

**Comment by EricRabil** [comment]
Woahh, my bad. I didn't realize it took URLs without the suite. Sorry for the confusion

**Comment by oprypin** [comment]
Well, it's not directly documented that it handles those, so not really your bad.

By the way, it *also* handles URLs in this format:

https://nightly.link/EricRabil/BBDash/suites/2569081819/artifacts/55984571

But the thing is, it doesn't use the suite id.
So this also works (but obviously the example in my previous message is preferred):

https://nightly.link/EricRabil/BBDash/suites/0/artifacts/55984571

**Comment by EricRabil** [comment]
Interesting & useful behavior. Thanks for the clarification

**Comment by oprypin** [comment]
> I'm making a nightly releases page that shows the latest artifacts

**By the way**, I hope you know that the main purpose of https://nightly.link/ *is* already to redirect to the latest artifact without first figuring out which exact one it is.

**Comment by EricRabil** [comment]
I do, I just want to also have a list that shows all of the builds (ultimately it’ll be kinda like dl.bukkit.org where you were able to scroll back through every build, but for me it’ll just drop artifacts if/when github expires them).

-- Eric Rabil ( ***@***.*** )

Sent via Superhuman iOS ( ***@***.*** )
