### ISSUE TITLE
Download latest returning not latest file

### ISSUE THREAD

**Issue by csparker247** [oprypin/nightly.link#2]
I have this [download latest link](https://nightly.link/csparker247/curriculum-vitae/workflows/build-doc/master/PDF.zip) for [this config](https://github.com/csparker247/curriculum-vitae/blob/master/.github/workflows/build-doc.yml). I just had to commit multiple times in quick succession, and now the latest link is currently redirecting me to the artifacts from one of the earlier builds. I can tell because I timestamp my artifacts.

This could be a bug or it could be due to some sort of rate limit. Any thoughts?

**Comment by oprypin** [comment]
For some reason GitHub doesn't consider that run as `is:success`???

https://github.com/csparker247/curriculum-vitae/actions?query=workflow:CI+branch:master+event:push
https://github.com/csparker247/curriculum-vitae/actions?query=workflow:CI+branch:master+event:push+is:success
(I use the latter)

Do you have any clue why it would do that?

**Comment by oprypin** [comment]
GitHub **just** updated itself so that this run is included into `is:success` page, but earlier it wasn't there, which is the issue.

**Comment by csparker247** [comment]
Well that's curious and weird! It definitely works now. 

I have no idea why it wouldn't have updated. Maybe because I pushed so many commits individually in quick succession? Anyway, thanks for your help! This is clearly just GH being GH. ¯\_(ツ)_/¯
