### ISSUE TITLE
Downgrade to OAuth App to avoid "Act on your behalf" request

### ISSUE THREAD

**Issue by PibePlayer** [oprypin/nightly.link#21]
I did yesterday an App like this to download the latest successful artifact from a GH Action on my public repo. I investigated all day long just to manage to do a extremely toned down version of this app, but while it's not as full fledged as this one, I managed to do it fully on Html + Js (if we forget about the CORB which I had to workaround with a nodejs app) and it doesn't ask for the strange things on the Auth page compared to the Github apps, check it out!:
![OAuth App Request](https://user-images.githubusercontent.com/3812153/117554811-5a9ba280-b030-11eb-8ef1-8aa472b85def.png)

**Comment by oprypin** [comment]
I spent a **ton** of time trying just this upon initial release, but this is infeasible. Some things are missing in OAuth APIs and other things can't be matched up with the App concepts.

**Note that nightly.link does not ask this permission at all for public repos.**
So, seeing as your example is only for public repos, I don't think you won anything.

And even when this permission *is* needed, the main page already explains that that wording is completely bogus and there's no connection between that screen and any actual permissions being granted. And that is something that each developer can verify independently: make an app with such a screen, go through it and see that the app hasn't actually gained any abilities.

**Comment by oprypin** [comment]
Thanks for sharing the idea though. I don't mean to shut down all conversation :)

Let me know if there's still something preventing you from using nightly.link itself.
I could also write instructions on self-hosting it, but so far nobody asked.

**Comment by PibePlayer** [comment]
By the way, it only asks for public ones since I limited it's scope on the last commit (from 'repo', to 'public_repo').
And there's nothing preventing me from using nightly.link but me wanting to see my project coming to fruition after more than 8 hours on it (since I didn't knew of it before).

**Comment by oprypin** [comment]
Meanwhile, nightly.link, being a GitHub App, lets you give permissions to particular repositories only, it doesn't ask "all private" or even "all public" repositories.
