### ISSUE TITLE
pr-comment not firing

### ISSUE THREAD

**Issue by jwvanderbeck** [oprypin/nightly.link#22]
Hi,

First apologies for what might be a really stupid issue.  CI/CD isn't my strong point, but I'm trying to get something up and running on a repo so that artifacts get attached to PRs for others to test.

I have a "build" action already that runs and uploads and artifact.  I am now trying to connect your pr-comment bot but it never seems to actually run.

I modified the workflow only to change `workflows: ['Test workflow with upload']` to `workflows: ['build']` which is the name of my other workflow.  I made no other changes.  Are there other things I should be changing?

**Comment by oprypin** [comment]
It's not possible to tell. Please share all involved workflow files.

**Comment by jwvanderbeck** [comment]
Ah it was not on the main branch yet as I was testing the stuff out still on `dev` so I'm sure that's the issue.

**Comment by jwvanderbeck** [comment]
Works now.  Perfect you are amazing and this is going to make our lives a million times easier.  Thank you!
