### ISSUE TITLE
Does not works for emoji branch name

### ISSUE THREAD

**Issue by codehz** [oprypin/nightly.link#24]
as title, got 404 every time

e.g.
https://github.com/codehz/death-origin-fabric/blob/%F0%9F%A7%AC/.github/workflows/build.yml
-> 
https://nightly.link/codehz/death-origin-fabric/workflows/build/%25F0%259F%25A7%25AC

**Comment by oprypin** [comment]
Hmm so the redirection form on the home page is faulty.

But actually seems like GitHub itself doesn't support this??
Compare:

* <https://api.github.com/repos/codehz/death-origin-fabric/actions/workflows/build.yml/runs>
* <https://api.github.com/repos/codehz/death-origin-fabric/actions/workflows/build.yml/runs?branch=🧬>

* <https://github.com/codehz/death-origin-fabric/actions?query=event:push+is:success>
* <https://github.com/codehz/death-origin-fabric/actions?query=event:push+is:success+branch:🧬>

**Comment by oprypin** [comment]
As described above, I fixed the problem on my side, but GitHub is still not handling it correctly on its side.
