### ISSUE TITLE
Support for alternative software forges?

### ISSUE THREAD

**Issue by SFR-git** [oprypin/nightly.link#25]
I'm interested in using nightly.link for artifacts on a repository cross-hosted on both GitHub and sourcehut, so that the CI packages the application for a wider range of operating systems. It'd be really great if I could use nightly.link as a main hub for all of the artifacts, instead of having to link to multiple separate places.

**Comment by oprypin** [comment]
This was part of the original sentiment behind the project -- with appropriate subdomains -- but ultimately I decided to only implement GitHub.

The thing is, I have no awareness of which other systems would need such functionality and I don't even use any other such systems, so my ability to support them would be very limited.

You only briefly mention sourcehut, but without comment on what functionality gap would need to be filled. I know nothing about it.

Overall I think that each separate supported system would have less than 30% code reuse and would need to be considered completely on its own. I can't make a blanket statement "I will" or "I will not" support other systems. Once an important enough system comes along, it can open the gates.

**Comment by oprypin** [comment]
Additionally, I am pretty sure nightly.link will never have hub pages spanning several systems, so to that part of your request it seems the answer is a direct "no". The current hub pages aren't meant to be end-user-facing, though I'm aware that there are such uses currently.

**Comment by SFR-git** [comment]
Fair enough. CI systems are different enough that implementing and maintaining more than one is a lot of maintenance. Thanks for the quick reply!
