### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by NotAProton** [oprypin/nightly.link#28]
![image](https://user-images.githubusercontent.com/81463636/133116864-7d3c6294-ca53-457b-abe3-7138eea36405.png)

**Comment by oprypin** [comment]
Hmm? Works for me.

**Comment by oprypin** [comment]
See also:
https://downforeveryoneorjustme.com/nightly.link

**Comment by NotAProton** [comment]
its working now, must have been my network

sorry for the trouble

**Comment by oprypin** [comment]
Hm there was something to this. I noticed at another time the server was having difficulties too, with the symptom of timeouts. I will follow a bit more closely. Thanks for the report.
