### ISSUE TITLE
No runs found for workflow 'build.yml' and branch 'master'

### ISSUE THREAD

**Issue by thirtythreeforty** [oprypin/nightly.link#3]
After hitting the bizarre "public users can't download artifacts" problem, I found your tool. Thanks!

I tried to provide the following URL for [thirtythreeforty/neolink](https://github.com/thirtythreeforty/neolink) after authorizing the app:

    https://github.com/thirtythreeforty/neolink/blob/master/.github/workflows/build.yaml

but I get the following error:

    {"code":404,"message":"No runs found for workflow 'build.yml' and branch 'master'"}

As far as I can tell, the workflow does everything right - it uses the upload action, and it exists on the `master` branch.  Am I holding it wrong, or is this a legitimate issue?

**Comment by oprypin** [comment]
Just GitHub API somehow giving it a 404. I don't see why as of yet. Maybe you can try to make sense of that before I get back to this.

https://api.github.com/repos/thirtythreeforty/neolink/actions/workflows/build.yml/runs?per_page=1&branch=master&event=push&status=success

**Comment by oprypin** [comment]
Oh. It's 'build.yaml', but the tool only wants 'build.yml' 🤔

**Comment by oprypin** [comment]
I'll look into a fix later unless you want to rename your workflow file 😳

**Comment by thirtythreeforty** [comment]
Ah gotcha. Thanks. Easy enough to rename the files, but I will leave this issue open because `.yaml` is an officially supported extension.
