### ISSUE TITLE
Link not working with "/" in branch name

### ISSUE THREAD

**Issue by CommanderRedYT** [oprypin/nightly.link#32]
When having a branch called "feature/foo", it kinda breaks the Branch-In-URL system (it says "Could not find branch feature")

**Comment by CommanderRedYT** [comment]
Update: It works, but only if the slash is encoded as %2F

**Comment by oprypin** [comment]
It definitely works and that is expected. If you use the forms, rather than typing the URL manually, it also substitutes correctly.

**Comment by YoshiRulz** [comment]
Did this regress? Pasting `https://github.com/mr-ke/BizHawk/blob/feature/librashader/.github/workflows/ci.yml` into the box on the landing page gives https://nightly.link/mr-ke/BizHawk/workflows/ci/feature%2Flibrashader?preview, which doesn't work.

**Comment by oprypin** [comment]
No, that whole repository gives 404, even for master.

Usually it's because the "GitHub app" was uninstalled
