### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by simonmichael** [oprypin/nightly.link#4]
Thanks for this service. I tried creating https://nightly.link/simonmichael/hledger/workflows/linux/master, but the hledger-ubuntu link there gives 500 internal server error. Granting access to the app didn't make a difference.

**Comment by oprypin** [comment]
`curl -v -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/simonmichael/hledger/actions/artifacts/9022516/zip`
In this case GitHub itself produces `500 Internal Server Error`:
```
{
  "message": "Failed to generate URL to download artifact",
  "documentation_url": "https://docs.github.com/rest/reference/actions#download-an-artifact"
}
```

---

I just generally don't forward these errors to the output in case GitHub's message discloses some secret.

**Comment by oprypin** [comment]
https://github.com/simonmichael/hledger/actions?query=workflow%3A%22linux+CI%22+event%3Apush+is%3Asuccess+branch%3Amaster
And in this particular case, it seems extremely likely that the artifact (from "6 months ago") is simply expired. Would be nice if GitHub actually reported that through the API but it doesn't.

**Comment by oprypin** [comment]
So I added explanations for these error messages.

But now I also see that you're using scheduled runs, which should've showed up here, but only "push" artifacts runs are considered, and they're old, which you didn't expect.

So I'll also support scheduled runs.

**Comment by simonmichael** [comment]
Thank you! Working now.
