### ISSUE TITLE
Site not working anymore

### ISSUE THREAD

**Issue by Slackadays** [oprypin/nightly.link#50]
I rely on nightly.link for Clipboard Builds here: https://github.com/Slackadays/Clipboard/actions/runs/4273223271/jobs/7439081624 and I'm getting an error both in those actions and on my end where nightly.link refuses to connect. Is this a known issue?

**Comment by H4kk3r3z** [comment]
Same

**Comment by PranavPurwar** [comment]
Same, i think the site is being ddos'ed or something.
