### ISSUE TITLE
Clickable Badge to Display Link Hit Count

### ISSUE THREAD

**Issue by manuc66** [oprypin/nightly.link#60]
Hello,

Thanks for your very usefull project!

I would like clickable badge that displays the actual number of link hits for artifacts within the repository. This feature would not only serve as a valuable asset to showcase the popularity and usage of the repository but also provide users with quick access to key statistics.

Do you have any idea how it could be achived ?

**Comment by oprypin** [comment]
Hi.
This website will not store analytics and will not provide this.
You can use any analytics solution which:
* Provides its own URL that redirects to nightly.link
* Provides a badge that displays hit counts to the above URL
