### ISSUE TITLE
Support URLs like "https://github.com/quassel/quassel/actions/workflows/main.yml" in the URL wizard

### ISSUE THREAD

**Issue by jcbhmr** [oprypin/nightly.link#62]
https://github.com/quassel/quassel/actions/workflows/main.yml
![image](https://github.com/oprypin/nightly.link/assets/61068799/05c19711-43b2-4938-ba72-2e000c3d3e39)

is essentially the same as https://github.com/quassel/quassel/blob/master/.github/workflows/main.yml

**Comment by oprypin** [comment]
Thanks, this is a good feature request.
Probably solvable just by duplicating this line and then changing it https://github.com/oprypin/nightly.link/blob/5a34469cc7939d3c6a79ad5badbc62971145fa57/src/nightly_link.cr#L152

And this test can be duplicated and edited
https://github.com/oprypin/nightly.link/blob/5a34469cc7939d3c6a79ad5badbc62971145fa57/spec/main_spec.cr#L82

Maybe I'll get around to it one day, in a week or so

**Comment by jcbhmr** [comment]
actually i think this is the same feature request as https://github.com/oprypin/nightly.link/issues/46 just using different words lol; this issue is a dup
