### ISSUE TITLE
404 on artifact link page with .zip artifact name suffix

### ISSUE THREAD

**Issue by grandchild** [oprypin/nightly.link#7]
Hi there,

thank you for offering this service! It's very nice for pre-stable-release software, such as my little project.

However I cannot seem to get it to work. I am sorry for opening what's basically a support ticket, but I tried to find out where the error is but couldn't so far.

This page correctly discovers the latest artifact name:

https://nightly.link/grandchild/linux_installer/workflows/installer-builder-installer/main

but the next page gives me a 404:

https://nightly.link/grandchild/linux_installer/workflows/installer-builder-installer/main/installer-builder

I fear there might be something wrong with my workflow file...

**Comment by oprypin** [comment]
It's a silly error, you'll see when I send the fix commit :weary:

What you can do now:

* Name your artifact "`installer-builder`", not "`installer-builder.zip`". Zip is always implied for artifacts.
    * You should do this regardless of the interaction with nightly.link

* Use https://nightly.link/grandchild/linux_installer/workflows/installer-builder-installer/main/installer-builder.zip.zip
    * Note: *this* one is not a mistake, it's saying "download the zip of the artifact `installer-builder.zip`"

**Comment by grandchild** [comment]
Ah I thought this might be the problem.

I will rename my artifact. I have to update it anyway so it's not a double zip.

Thank you! Do you want to keep this issue open until you fix it or should I close it?

**Comment by oprypin** [comment]
Keep open
